--- a/Dockerfile.patch
+++ b/Dockerfile.patch
@@ -1,6 +1,6 @@
 # https://docs.ghost.org/supported-node-versions/
 # https://github.com/nodejs/LTS
-FROM node:6-slim
+FROM hypriot/rpi-node:6-slim
 
 # grab gosu for easy step-down from root
 ENV GOSU_VERSION 1.10
