--- a/1/debian/Dockerfile
+++ b/1/debian/Dockerfile
@@ -1,6 +1,11 @@
 # https://docs.ghost.org/supported-node-versions/
 # https://github.com/nodejs/LTS
-FROM node:6-slim
+FROM hypriot/rpi-node:6
+
+ADD qemu-arm-static /usr/bin
+
+RUN groupadd --gid 1000 node \
+        && useradd --uid 1000 --gid node --shell /bin/bash --create-home node
 
 # grab gosu for easy step-down from root
 ENV GOSU_VERSION 1.10
@@ -19,6 +24,7 @@ ENV NODE_ENV production
 ENV GHOST_CLI_VERSION 1.1.3
 ENV GHOST_VERSION 1.15.0
 
+RUN npm config set unsafe-perm true
 RUN npm install -g "ghost-cli@$GHOST_CLI_VERSION" knex-migrator@latest
 
 ENV GHOST_INSTALL /var/lib/ghost
